name = "hypepaper-frontend"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
# This file is mainly for reference - Pages uses git integration

[site]
bucket = "./dist"

# Environment variables (set in Cloudflare dashboard)
# VITE_API_URL - Your Railway backend URL
# VITE_SUPABASE_URL - Your Supabase project URL
# VITE_SUPABASE_ANON_KEY - Your Supabase anon key
