version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: hypepaper-db
    environment:
      POSTGRES_DB: hypepaper
      POSTGRES_USER: hypepaper
      POSTGRES_PASSWORD: hypepaper_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hypepaper"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
