# Nixpacks configuration for Railway deployment
# This tells Railway to deploy the Python FastAPI backend

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "cd backend",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'No build step needed for Python'"]

[start]
cmd = "cd backend && uvicorn src.main:app --host 0.0.0.0 --port $PORT"
