name: Deploy to Cloudflare Pages and Railway

on:
  push:
    branches:
      - main
      - claude/**
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'http://localhost:8000' }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || '' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || '' }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          retention-days: 7

  deploy-frontend:
    name: Deploy Frontend to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: build-frontend
    # Only run on main branch
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Deploy to Cloudflare Pages
        # Skip if API token not configured
        if: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hypepaper
          directory: frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Cloudflare Token Not Configured
        if: ${{ secrets.CLOUDFLARE_API_TOKEN == '' }}
        run: |
          echo "ℹ️  Cloudflare API token not configured"
          echo "📋 See docs/working/ADD_CLOUDFLARE_API_TOKEN.md for setup instructions"

  deploy-backend:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest
    # Only run on main branch - Railway has GitHub integration for auto-deploy
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Railway Deployment
        run: |
          echo "✅ Code pushed to main branch"
          echo "🚂 Railway will auto-deploy via GitHub integration"
          echo "📊 Monitor deployment at: https://railway.app/dashboard"
        continue-on-error: true
